version: '3.5'

# Adapted from https://github.com/khezen/compose-postgres/blob/master/docker-compose.yml
services:
  db:
    container_name: postgres
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    # volumes:
    #    - postgres:/data/postgres
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    # volumes:
    #    - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"

# volumes:
#     postgres:
#     pgadmin: