version: '3.5'

services:
  server:
    container_name: tigertodo
    image: dstough/tigertodo
    restart: always
    env_file: 
      - .env
    environment: 
      - POSTGRES_HOSTNAME=db
    ports:
      - "80:3000"